entry: gh-start
executions:
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-actions-checkout-v4-1-1-squirrel-mango-raspberry
      port: exec
connections:
  - src:
      node: gh-secret-v1-elephant-yellow-rabbit
      port: secret
    dst:
      node: gh-actions-checkout-v4-1-1-squirrel-mango-raspberry
      port: token
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: -270
      y: -740
    settings:
      folded: false
  - id: gh-actions-checkout-v4-1-1-squirrel-mango-raspberry
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 140
      y: -170
    settings:
      folded: false
  - id: gh-secret-v1-elephant-yellow-rabbit
    type: gh-secret@v1
    position:
      x: -290
      y: 370
    inputs:
      name: secrets.GITHUB_TOKEN
    settings:
      folded: false
registries:
  - github.com/docker/setup-qemu-action@v3.0.0
  - github.com/docker/setup-buildx-action@v3.1.0
  - github.com/actions/cache@v4.0.0
  - github.com/satackey/action-docker-layer-caching@v0.0.11
  - github.com/oxsecurity/megalinter@v7.9.0
  - github.com/actions/upload-artifact@v4.3.1
  - github.com/oxsecurity/megalinter@v7
  - github.com/djbender/docker-buildx-pull-or-build@v0.5
  - github.com/actions/checkout@v4.1.1
description: ''
