entry: gh-start
executions:
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-actions-checkout-v4-1-1-squirrel-mango-raspberry
      port: exec
  - src:
      node: gh-actions-checkout-v4-1-1-squirrel-mango-raspberry
      port: exec
    dst:
      node: gh-oxsecurity-megalinter-v7-9-0-mango-plum-orange
      port: exec
connections:
  - src:
      node: gh-secret-v1-elephant-yellow-rabbit
      port: secret
    dst:
      node: gh-actions-checkout-v4-1-1-squirrel-mango-raspberry
      port: token
  - src:
      node: env-array-v1-red-snake-lion
      port: env
    dst:
      node: gh-oxsecurity-megalinter-v7-9-0-mango-plum-orange
      port: env
  - src:
      node: env-get-v1-monkey-plum-giraffe
      port: env
    dst:
      node: env-array-v1-red-snake-lion
      port: env[0]
  - src:
      node: env-get-v1-rabbit-dolphin-penguin
      port: env
    dst:
      node: env-array-v1-red-snake-lion
      port: env[1]
  - src:
      node: env-get-v1-parrot-koala-silver
      port: env
    dst:
      node: env-array-v1-red-snake-lion
      port: env[2]
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: -250
      y: -740
    settings:
      folded: false
  - id: gh-actions-checkout-v4-1-1-squirrel-mango-raspberry
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 200
      y: -570
    settings:
      folded: false
  - id: gh-secret-v1-elephant-yellow-rabbit
    type: gh-secret@v1
    position:
      x: -340
      y: 200
    inputs:
      name: secrets.GITHUB_TOKEN
    settings:
      folded: false
  - id: gh-oxsecurity-megalinter-v7-9-0-mango-plum-orange
    type: github.com/oxsecurity/megalinter@190cd0dad6dc52b2de5b810e3b290c3d6bdcc0f2
    position:
      x: 730
      y: -40
    settings:
      folded: false
  - id: env-array-v1-red-snake-lion
    type: env-array@v1
    position:
      x: 420
      y: 200
    inputs:
      env[0]: ''
      env[1]: ''
      env[2]: ''
    settings:
      folded: false
  - id: env-get-v1-monkey-plum-giraffe
    type: env-get@v1
    position:
      x: 100
      y: 200
    inputs:
      env: GITHUB_TOKEN
    settings:
      folded: false
  - id: env-get-v1-rabbit-dolphin-penguin
    type: env-get@v1
    position:
      x: 100
      y: 320
    inputs:
      env: VALIDATE_ALL_CODEBASE
    settings:
      folded: false
  - id: env-get-v1-parrot-koala-silver
    type: env-get@v1
    position:
      x: 100
      y: 440
    inputs:
      env: GITHUB_WORKSPACE
    settings:
      folded: false
registries:
  - github.com/docker/setup-qemu-action@v3.0.0
  - github.com/docker/setup-buildx-action@v3.1.0
  - github.com/actions/cache@v4.0.0
  - github.com/satackey/action-docker-layer-caching@v0.0.11
  - github.com/oxsecurity/megalinter@v7.9.0
  - github.com/actions/upload-artifact@v4.3.1
  - github.com/oxsecurity/megalinter@v7
  - github.com/djbender/docker-buildx-pull-or-build@v0.5
  - github.com/actions/checkout@v4.1.1
description: ''
