entry: gh-start
executions:
  - src:
      node: gh-actions-checkout-v4-1-1-green-cranberry-dolphin
      port: exec
    dst:
      node: gh-sigstore-cosign-installer-v3-4-0-gold-dog-kangaroo
      port: exec
  - src:
      node: gh-docker-setup-buildx-action-v3-1-0-mango-cat-kiwi
      port: exec
    dst:
      node: gh-docker-login-action-v3-0-0-peach-giraffe-dog
      port: exec
  - src:
      node: gh-docker-login-action-v3-0-0-peach-giraffe-dog
      port: exec
    dst:
      node: gh-actions-cache-silver-butterfly-brown
      port: exec
  - src:
      node: gh-actions-cache-silver-butterfly-brown
      port: exec
    dst:
      node: gh-docker-metadata-action-v5-5-1-elephant-pineapple-green
      port: exec
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-actions-checkout-v4-1-1-green-cranberry-dolphin
      port: exec
  - src:
      node: gh-docker-metadata-action-v5-5-1-elephant-pineapple-green
      port: exec
    dst:
      node: gh-docker-build-push-action-v5-1-0-apple-zebra-koala
      port: exec
  - src:
      node: gh-docker-build-push-action-v5-1-0-apple-zebra-koala
      port: exec
    dst:
      node: run-v1-pineapple-squirrel-elephant
      port: exec
  - src:
      node: gh-sigstore-cosign-installer-v3-4-0-gold-dog-kangaroo
      port: exec
    dst:
      node: gh-docker-setup-buildx-action-v3-1-0-mango-cat-kiwi
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 250
      y: 1050
    settings:
      folded: true
  - id: gh-actions-checkout-v4-1-1-green-cranberry-dolphin
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 530
      y: 1040
    settings:
      folded: true
  - id: gh-sigstore-cosign-installer-v3-4-0-gold-dog-kangaroo
    type: >-
      github.com/sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4
    position:
      x: 970
      y: 1250
    settings:
      folded: true
  - id: gh-docker-setup-buildx-action-v3-1-0-mango-cat-kiwi
    type: >-
      github.com/docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c
    position:
      x: 1430
      y: 900
    inputs:
      version: latest
    settings:
      folded: true
  - id: gh-docker-login-action-v3-0-0-peach-giraffe-dog
    type: github.com/docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
    position:
      x: 1840
      y: 1560
    inputs:
      env: []
      registry: env.REGISTRY
      password: secrets.DOCKERHUB_PASSWORD
      username: secrets.DOCKERHUB_USERNAME
    settings:
      folded: true
  - id: gh-actions-cache-silver-butterfly-brown
    type: github.com/actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
    position:
      x: 2210
      y: 1510
    inputs:
      path: /tmp/.buildx-cache
      key: ${{ runner.os }}-buildx-${{ github.sha }}
      restore-keys: ${{ runner.os }}-buildx-
    settings:
      folded: true
  - id: gh-docker-metadata-action-v5-5-1-elephant-pineapple-green
    type: github.com/docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
    position:
      x: 2660
      y: 1110
    inputs:
      images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    settings:
      folded: false
  - id: gh-docker-build-push-action-v5-1-0-apple-zebra-koala
    type: >-
      github.com/docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
    position:
      x: 3040
      y: 710
    inputs:
      push: 'true'
      context: .
      platforms: linux/amd64,linux/arm64
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    settings:
      folded: false
  - id: run-v1-pineapple-squirrel-elephant
    type: run@v1
    position:
      x: 3470
      y: 1290
    inputs:
      script: >-
        cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{
        steps.build-and-push.outputs.digest }}
      env:
        - ''
    settings:
      folded: false
registries:
  - github.com/actions/checkout@v4.1.1
  - github.com/sigstore/cosign-installer@v3.4.0
  - github.com/docker/setup-buildx-action@v3.1.0
  - github.com/docker/login-action@v3.0.0
  - github.com/docker/metadata-action@v5.5.1
  - github.com/docker/build-push-action@v5.1.0
description: ''
