entry: gh-start
executions:
  - src:
      node: gh-checkout
      port: exec
    dst:
      node: gh-docker-setup-qemu-action-v3-0-0-red-purple-pomegranate
      port: exec
  - src:
      node: gh-docker-setup-buildx-action-v3-1-0-dolphin-brown-pineapple
      port: exec
    dst:
      node: run-v1-pomegranate-silver-squirrel
      port: exec
  - src:
      node: run-v1-pomegranate-silver-squirrel
      port: exec-success
    dst:
      node: run-v1-koala-brown-orange
      port: exec
  - src:
      node: run-v1-koala-brown-orange
      port: exec-success
    dst:
      node: gh-actions-cache-v4-0-0-squirrel-orange-snake
      port: exec
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-checkout
      port: exec
  - src:
      node: branch-v1-squirrel-dog-penguin
      port: exec-then
    dst:
      node: gh-oxsecurity-megalinter-v7-plum-lion-penguin
      port: exec
  - src:
      node: gh-actions-cache-v4-0-0-squirrel-orange-snake
      port: exec
    dst:
      node: branch-v1-squirrel-dog-penguin
      port: exec
connections:
  - src:
      node: env-get-v1-cherry-zebra-silver
      port: env
    dst:
      node: string-match-v1-lemon-purple-pear
      port: str1
  - src:
      node: string-match-v1-lemon-purple-pear
      port: result
    dst:
      node: branch-v1-squirrel-dog-penguin
      port: condition
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: -180
      y: -270
    settings:
      folded: false
  - id: gh-checkout
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 230
      y: -80
    inputs:
      token: ${{ secrets.GITHUB_TOKEN }}
    settings:
      folded: false
  - id: gh-docker-setup-qemu-action-v3-0-0-red-purple-pomegranate
    type: >-
      github.com/docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
    position:
      x: 740
      y: 80
    settings:
      folded: false
  - id: gh-docker-setup-buildx-action-v3-1-0-dolphin-brown-pineapple
    type: >-
      github.com/docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c
    position:
      x: 1120
      y: -60
    inputs:
      version: latest
    settings:
      folded: false
  - id: run-v1-pomegranate-silver-squirrel
    type: run@v1
    position:
      x: 1590
      y: -0.0
    inputs:
      script: >-
        echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]'
        '[:lower:]')" >> $GITHUB_ENV
    settings:
      folded: false
  - id: run-v1-koala-brown-orange
    type: run@v1
    position:
      x: 1970
      y: -0.0
    inputs:
      script: >-
        echo "{key}=$(echo $IMAGE_NAME | sha256sum | cut -d ' ' -f 1)" >>
        $GITHUB_OUTPUT
    settings:
      folded: false
  - id: gh-actions-cache-v4-0-0-squirrel-orange-snake
    type: github.com/actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
    position:
      x: 2330
      y: -90
    inputs:
      path: /tmp/.docker-caache
      key: ${{ runner.os }}-docker-${{ steps.cache-key.outputs.key }}
      restore-keys: ${{ runner.os }}-docker-
    settings:
      folded: false
  - id: gh-oxsecurity-megalinter-v7-plum-lion-penguin
    type: github.com/oxsecurity/megalinter@190cd0dad6dc52b2de5b810e3b290c3d6bdcc0f2
    position:
      x: 3500
      y: -60
    inputs:
      env:
        - ''
        - ''
    settings:
      folded: false
  - id: env-get-v1-cherry-zebra-silver
    type: env-get@v1
    position:
      x: 2720
      y: -70
    inputs:
      env: VALIDATE_ALL_CODEBASE
    settings:
      folded: false
  - id: string-fmt-v1-brown-rabbit-cranberry
    type: string-fmt@v1
    position:
      x: 2740
      y: 460
    inputs:
      input[0]: null
      fmt: '%v'
    settings:
      folded: false
  - id: branch-v1-squirrel-dog-penguin
    type: branch@v1
    position:
      x: 3280
      y: -60
    inputs:
      condition: true
    settings:
      folded: false
  - id: string-match-v1-lemon-purple-pear
    type: string-match@v1
    position:
      x: 2970
      y: 20
    inputs:
      op: equals
      str2: 'true'
    settings:
      folded: false
registries:
  - github.com/docker/setup-qemu-action@v3.0.0
  - github.com/docker/setup-buildx-action@v3.1.0
  - github.com/actions/cache@v4.0.0
  - github.com/satackey/action-docker-layer-caching@v0.0.11
  - github.com/oxsecurity/megalinter@v7.9.0
  - github.com/actions/upload-artifact@v4.3.1
  - github.com/oxsecurity/megalinter@v7
  - github.com/djbender/docker-buildx-pull-or-build@v0.5
description: ''
