entry: gh-start
executions:
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-checkout
      port: exec
  - src:
      node: gh-checkout
      port: exec
    dst:
      node: gh-docker-setup-qemu-action-v3-0-0-red-purple-pomegranate
      port: exec
  - src:
      node: gh-docker-setup-qemu-action-v3-0-0-red-purple-pomegranate
      port: exec
    dst:
      node: gh-docker-setup-buildx-action-v3-1-0-dolphin-brown-pineapple
      port: exec
  - src:
      node: gh-docker-setup-buildx-action-v3-1-0-dolphin-brown-pineapple
      port: exec
    dst:
      node: run-v1-pomegranate-silver-squirrel
      port: exec
  - src:
      node: run-v1-pomegranate-silver-squirrel
      port: exec-success
    dst:
      node: run-v1-koala-brown-orange
      port: exec
  - src:
      node: run-v1-koala-brown-orange
      port: exec-success
    dst:
      node: gh-actions-cache-v4-0-0-squirrel-orange-snake
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 100
      y: 100
    settings:
      folded: true
  - id: gh-checkout
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 450
      y: 100
    settings:
      folded: true
  - id: gh-docker-setup-qemu-action-v3-0-0-red-purple-pomegranate
    type: >-
      github.com/docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
    position:
      x: 890
      y: 80
    settings:
      folded: true
  - id: gh-docker-setup-buildx-action-v3-1-0-dolphin-brown-pineapple
    type: >-
      github.com/docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c
    position:
      x: 1240
      y: 50
    settings:
      folded: true
  - id: run-v1-pomegranate-silver-squirrel
    type: run@v1
    position:
      x: 1620
      y: 120
    inputs:
      script: >-
        echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]'
        '[:lower:]')" >> $GITHUB_ENV
    settings:
      folded: true
  - id: run-v1-koala-brown-orange
    type: run@v1
    position:
      x: 1950
      y: 130
    inputs:
      script: >-
        echo "::set-output name=key::$(echo $IMAGE_NAME | sha256sum | cut -d ' '
        -f 1)"
    settings:
      folded: false
  - id: gh-actions-cache-v4-0-0-squirrel-orange-snake
    type: github.com/actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
    position:
      x: 2330
      y: 110
    inputs:
      path: /tmp/.docker-caache
      key: ${{ runner.os }}-docker-${{ steps.cache-key.outputs.key }}
      restore-keys: ${{ runner.os }}-docker-
    settings:
      folded: false
registries:
  - github.com/docker/setup-qemu-action@v3.0.0
  - github.com/docker/setup-buildx-action@v3.1.0
  - github.com/actions/cache@v4.0.0
description: ''
