entry: gh-start
executions:
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-checkout
      port: exec
  - src:
      node: gh-oxsecurity-megalinter-v7-plum-lion-penguin
      port: exec
    dst:
      node: gh-actions-upload-artifact-dolphin-watermelon-panda
      port: exec
  - src:
      node: gh-checkout
      port: exec
    dst:
      node: gh-docker-setup-qemu-action-v3-0-0-gold-yellow-octopus
      port: exec
  - src:
      node: gh-docker-setup-qemu-action-v3-0-0-gold-yellow-octopus
      port: exec
    dst:
      node: gh-docker-setup-buildx-action-v3-1-0-silver-cranberry-strawberry
      port: exec
  - src:
      node: gh-docker-setup-buildx-action-v3-1-0-silver-cranberry-strawberry
      port: exec
    dst:
      node: run-v1-pomegranate-silver-squirrel
      port: exec
  - src:
      node: run-v1-pomegranate-silver-squirrel
      port: exec-success
    dst:
      node: run-v1-koala-brown-orange
      port: exec
  - src:
      node: run-v1-koala-brown-orange
      port: exec-success
    dst:
      node: gh-actions-cache-v4-0-0-squirrel-orange-snake
      port: exec
  - src:
      node: gh-actions-cache-v4-0-0-squirrel-orange-snake
      port: exec
    dst:
      node: gh-oxsecurity-megalinter-v7-plum-lion-penguin
      port: exec
connections:
  - src:
      node: string-fmt-v1-parrot-kangaroo-monkey
      port: result
    dst:
      node: gh-actions-upload-artifact-dolphin-watermelon-panda
      port: path
  - src:
      node: env-get-v1-squirrel-cherry-squirrel
      port: env
    dst:
      node: env-array-v1-pear-gold-monkey
      port: env[0]
  - src:
      node: gh-secret-v1-green-blue-yellow
      port: secret
    dst:
      node: gh-checkout
      port: token
  - src:
      node: gh-secret-v1-lion-pear-orange
      port: secret
    dst:
      node: env-array-v1-pear-gold-monkey
      port: env[1]
  - src:
      node: env-array-v1-pear-gold-monkey
      port: env
    dst:
      node: gh-oxsecurity-megalinter-v7-plum-lion-penguin
      port: env
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: -400
      y: -430
    settings:
      folded: false
  - id: gh-checkout
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 230
      y: -80
    inputs:
      token: ${{ secrets.GITHUB_TOKEN }}
    settings:
      folded: false
  - id: run-v1-pomegranate-silver-squirrel
    type: run@v1
    position:
      x: 1590
      y: -0.0
    inputs:
      script: >-
        echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]'
        '[:lower:]')" >> $GITHUB_ENV
    settings:
      folded: false
  - id: run-v1-koala-brown-orange
    type: run@v1
    position:
      x: 1970
      y: -0.0
    inputs:
      script: >-
        echo "{key}=$(echo $IMAGE_NAME | sha256sum | cut -d ' ' -f 1)" >>
        $GITHUB_OUTPUT
    settings:
      folded: false
  - id: gh-actions-cache-v4-0-0-squirrel-orange-snake
    type: github.com/actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
    position:
      x: 2330
      y: -90
    inputs:
      path: /tmp/.docker-caache
      key: ${{ runner.os }}-docker-${{ steps.cache-key.outputs.key }}
      restore-keys: ${{ runner.os }}-docker-
    settings:
      folded: false
  - id: gh-oxsecurity-megalinter-v7-plum-lion-penguin
    type: github.com/oxsecurity/megalinter@190cd0dad6dc52b2de5b810e3b290c3d6bdcc0f2
    position:
      x: 3390
      y: -250
    inputs:
      env:
        - ''
        - ''
    settings:
      folded: false
  - id: gh-actions-upload-artifact-dolphin-watermelon-panda
    type: >-
      github.com/actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
    position:
      x: 3640
      y: -120
    inputs:
      name: Megalinter Reports
    settings:
      folded: false
  - id: string-fmt-v1-parrot-kangaroo-monkey
    type: string-fmt@v1
    position:
      x: 3210
      y: 300
    inputs:
      input[0]: null
      fmt: '| megalinter-reports mega-linter.log'
    settings:
      folded: false
  - id: gh-docker-setup-qemu-action-v3-0-0-gold-yellow-octopus
    type: >-
      github.com/docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
    position:
      x: 710
      y: -20
    settings:
      folded: false
  - id: gh-docker-setup-buildx-action-v3-1-0-silver-cranberry-strawberry
    type: >-
      github.com/docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c
    position:
      x: 1130
      y: -80
    settings:
      folded: false
  - id: env-array-v1-pear-gold-monkey
    type: env-array@v1
    position:
      x: 3150
      y: -60
    inputs:
      env[0]: VALIDATE_ALL_CODEBASE=true
      env[1]: ''
    settings:
      folded: false
  - id: gh-secret-v1-lion-pear-orange
    type: gh-secret@v1
    position:
      x: 2740
      y: 110
    inputs:
      name: GITHUB_TOKEN
    settings:
      folded: false
  - id: env-get-v1-squirrel-cherry-squirrel
    type: env-get@v1
    position:
      x: 2860
      y: -30
    inputs:
      env: VALIIDATE_ALL_CODEBASE
    settings:
      folded: false
  - id: gh-secret-v1-green-blue-yellow
    type: gh-secret@v1
    position:
      x: -230
      y: 510
    inputs:
      name: GITHUB_TOKEN
    settings:
      folded: false
registries:
  - github.com/docker/setup-qemu-action@v3.0.0
  - github.com/docker/setup-buildx-action@v3.1.0
  - github.com/actions/cache@v4.0.0
  - github.com/satackey/action-docker-layer-caching@v0.0.11
  - github.com/oxsecurity/megalinter@v7.9.0
  - github.com/actions/upload-artifact@v4.3.1
  - github.com/oxsecurity/megalinter@v7
  - github.com/djbender/docker-buildx-pull-or-build@v0.5
description: ''
