name: Github Actions test
run-name: ${{ github.actor }} is running
on: [push]
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} server."
      - run: echo "The name of the branch is ${{ github.ref }}. The name of the repo is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to ${{ github.workspace }}"
      - name: List files in repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}"
