name: autofix.ci
on: [push, pull_request]
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm dlx prettier --write .

      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84

      # - name: Trigger CI Workflow
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     event-type: 'autofix-completed'
