name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  schedule:
    - cron: '0 0 * * 0'

permissions:
  actions: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      - run: pnpm exec nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      # Cache node_modules
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile

      - uses: nrwl/nx-set-shas@v4.0.4

      - run: pnpm exec nx-cloud record -- nx format:write
      - run: pnpm exec nx affected -t lint test build

      - name: Archive AppMaps
        uses: getappmap/analyze-action@v1
        with:
          project-summary: true
          verbose: true

      - name: Save AppMaps
        uses: actions/cache/save@v4.0.0
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

  appmap-analysis:
    if: always()
    needs: [main]
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write
