name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  schedule:
    - cron: '0 0 * * 0'

permissions:
  actions: read
  pull-requests: write
  contents: write
  checks: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

  #     - uses: pnpm/action-setup@v3
  #       with:
  #         version: 8
  #     # Cache node_modules
  #     - uses: actions/setup-node@v4.0.2
  #       with:
  #         node-version: 20
  #         cache: 'pnpm'
  #     - run: pnpm install --no-frozen-lockfile

  #     - uses: nrwl/nx-set-shas@v4.0.4

  #     - run: pnpm exec nx-cloud record -- nx format:write
  #     - run: pnpm exec nx affected -t lint test build

  #     - name: Analyze AppMaps
  #       if: always()
  #       uses: getappmap/analyze-action@v1
  #       with:
  #         project-summary: true
  #         verbose: true

  #     - name: Save AppMaps
  #       uses: actions/cache/save@v4.0.0
  #       if: always()
  #       with:
  #         path: ./tmp/appmap
  #         key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

  #     - name: Upload coverage reports to Codecov
  #       uses: codecov/codecov-action@v4.0.1
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         slug: AReid987/career-compass
  #         verbose: true

  # appmap-analysis:
  #   if: always()
  #   needs: [main]
  #   uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
  #   permissions:
  #     actions: read
  #     contents: read
  #     checks: write
  #     pull-requests: write
