name: MegaLinter ActionForge

on: [push]

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit
  REGISTRY: docker.io
  VALIDATE_ALL_CODEBASE: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-publish:
    name: MegaLinter ActionForge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Execute Action Graph
        uses: actionforge/action@919d415a6b6e22919f7e115cf594ae52ded95041 # v0.8.32
        with:
          graph_file: mega-linter-af.yml
          token: ${{ secrets.GITHUB_TOKEN }}

        env:
          APPLY_FIXES: all
          APPLY_FIXES_EVENT: all
          APPLY_FIXES_MODE: commit
          REGISTRY: docker.io
          VALIDATE_ALL_CODEBASE: 'true'
