# MegaLinter GitHub Action configuration
# https://megalinter.io
name: MegaLinter

on:
  # Trigger mega-linter on every push
  push:
  pull_request:
    branches: [main]

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: ScribeMD Docker Cache
        uses: ScribeMD/docker-cache@e481e638abdb45e2fa30845305c387a544cc617f
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Cache Docker layers
        uses: actions/cache@v4.0.0
        with:
          path: /tmp/.docker-images
          key: ${{ runner.os }}-docker-image-oxsecurity-megalinter-latest
          restore-keys: |
            ${{ runner.os }}-docker-image-oxsecurity-megalinter-
      - name: Load cached Docker image
        run: |
          if [ -f "/tmp/.docker-images/megalinter.tar"]; then
            docker load -i /tmp/.docker-images/megalinter.tar
          fi
      - name: Pull and Save Docker Image
        run: |
          if ! docker images oxsecurity/megalinter | grep -q oxsecurity/megalinter; then
            docker pull oxsecurity/megalinter:latest
            mkdir -p /tmp/.docker-images
            docker save oxsecurity/megalinter:latest > /tmp/.docker-images/megalinter.tar
          fi
      - name: Log in to Dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull and Build Docker Image
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: user/app:latest

      - name: Move and Save Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: MegaLinter
        id: ml
        # https://megalinter.io/flavors
        uses: oxsecurity/megalinter@190cd0dad6dc52b2de5b810e3b290c3d6bdcc0f2
        env:
          #  https://megalinter.io/configuration
          VALIDATE_ALL_CODEBASE: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            megalinter.log
      #  Create pull request if applicablie
      - name: Create Pull Request with applied fixes
        id: cpr
        if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          commit-message: '[MegaLinter] Apply linters automatic fixes'
          title: '[MegaLinter] Apply linters automatic fixes'
          labels: bot

      - name: Create PR output
        if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
        run: sudo chown -Rc $UID .git/

      - name: Commit and push applied linter fixes
        if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
        uses: stefanzweifel/git-auto-commit-action@e040c596f0a65570b339c60818081175bcf82d11
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: '[MegaLinter] Apply linters fixes'
          commit_user_name: megalinter-bot
          commit_user_email: read.musik@gmail.com
