name: MegaLinter ActionForge

on: [push]

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit
  REGISTRY: docker.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: MegaLinter ActionForge
    steps:
      - name: Execute Action Graph
        uses: actionforge/action@919d415a6b6e22919f7e115cf594ae52ded95041 # v0.8.31
        with:
          graph_file: mega-linter-af.yml
