name: MegaLinter Actionforge

on:
  push:
  pull_request:
    branches: [main]

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository.lowercase }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Execute Action Graph
        uses: actionforge/action@919d415a6b6e22919f7e115cf594ae52ded95041 # v0.8.31
        with:
          graph_file: mega-linter-af.yml
