name: MegaLinter ActionForge

on: [push]

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit
  REGISTRY: docker.io
  VALIDATE_ALL_CODEBASE: 'true'
  GITHUB_WORKSPACE: /github/workspace

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-publish:
    name: MegaLinter ActionForge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Execute Action Graph
        uses: actionforge/action@afc00b0a012597ec831aa126138f170696e5370a # v0.8.31
        with:
          graph_file: mega-linter-af.yml
          token: ${{ secrets.GITHUB_TOKEN }}

        env:
          APPLY_FIXES: all
          APPLY_FIXES_EVENT: all
          APPLY_FIXES_MODE: commit
          REGISTRY: docker.io
          VALIDATE_ALL_CODEBASE: 'true'
